# .github/actions/setup/action.yaml
name: Set Up Test Environment Action
description: Setup action
runs:
  using: composite
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-12 valgrind
      shell: bash
    - run: |
        echo "Iy" | bash -c 'bash <(curl -s https://raw.githubusercontent.com/tmatis/funcheck/main/scripts/install.sh)'
      shell: bash