version: '3'
services:
  run-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
    volumes:
      - .:/app
    environment:
      - USER=${USER}
    user: root
    command: ["sh", "-c", "sleep infinity"]
